version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test

workflows:
  sample:
    jobs:
      - build-and-test
