module.exports = [
  // empty block
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '  }',
      '  output {',
      '    "- {name}"',
      '  }',
      '}',
    ],
    output: [
    ],
  },
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '  }',
      '  output {',
      '  }',
      '}',
    ],
    output: [
    ],
  },

  // empty line
  {
    items: [
      ['100', 'item01', 100, []],
      ['200', 'item02', 200, []],
      ['300', 'item03', 300, []],
    ],
    input: [
      'report {',
      ' ',
      '  code {',
      ' ',
      '    100',
      ' ',
      '    200',
      '    300',
      ' ',
      '  }',
      ' ',
      '  output {',
      ' ',
      '    if (amount == 100) {',
      ' ',
      '      "# code:#{code}"',
      ' ',
      '    } elseif (amount == 200) {',
      ' ',
      '      "# code:#{code}"',
      ' ',
      '    } else {',
      ' ',
      '      "# code:#{code}"',
      ' ',
      '    }',
      ' ',
      '  }',
      ' ',
      '}',
    ],
    output: [
      '# code:100',
      '# code:200',
      '# code:300',
    ],
  },
  {
    items: [
      ['100', 'item01', 100, []],
      ['200', 'item02', 200, []],
      ['300', 'item03', 300, []],
    ],
    input: [
      'report {',
      '',
      '  code {',
      '',
      '    100',
      '',
      '    200',
      '    300',
      '',
      '  }',
      '',
      '  output {',
      '',
      '    if (amount == 100) {',
      '',
      '      "# code:#{code}"',
      '',
      '    } elseif (amount == 200) {',
      '',
      '      "# code:#{code}"',
      '',
      '    } else {',
      '',
      '      "# code:#{code}"',
      '',
      '    }',
      '',
      '  }',
      '',
      '}',
    ],
    output: [
      '# code:100',
      '# code:200',
      '# code:300',
    ],
  },

  // empty condition block
  {
    items: [
      ['100', 'item01', 100],
      ['200', 'item02', 200],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '  }',
      '  output {',
      '    if (true) {',
      '    } else {',
      '    }',
      '  }',
      '}',
    ],
    output: [
    ],
  },

  // loop
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy']],
      ['200', 'item02', 200, ['zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '  }',
      '  output {',
      '    "# code:#{code} {#{name},#{amount}}"',
      '    for (comment in comments) {',
      '      "- #{comment}"',
      '    }',
      '  }',
      '}',
    ],
    output: [
      '# code:100 {item01,100}',
      '- xxx',
      '- yyy',
      '# code:200 {item02,200}',
      '- zzz',
    ],
  },

  // condition and loop
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
      ['200', 'item02', 200, ['zzz']],
      ['300', 'item03', 300, []],
      ['400', 'item04', 400, []],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '    300',
      '  }',
      '  output {',
      '    if (amount <= 100) {',
      '      "# code:#{code} {#{name},#{amount}}"',
      '      for (comment in comments) {',
      '        if (comment != "yyy") {',
      '          "- #{comment}"',
      '        }',
      '      }',
      '    } elseif (amount < 300) {',
      '    } else {',
      '      "# code:#{code} {#{name},#{amount}} (excess)"',
      '    }',
      '  }',
      '}',
    ],
    output: [
      '# code:100 {item01,100}',
      '- xxx',
      '- zzz',
      '# code:300 {item03,300} (excess)',
    ],
  },

  // complex condition
  {
    items: [
      ['100', 'item01', 100, []],
      ['200', 'item02', 200, []],
      ['300', 'item03', 300, []],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '    300',
      '  }',
      '  output {',
      '    if (amount == 1 || true) {',
      '      "# code:#{code} (01)"',
      '    }',
      '    if (amount == 1 || amount <= 100 || true) {',
      '      "# code:#{code} (02)"',
      '    }',
      '    if (amount == 1 || true && amount < 100) {',
      '      "# code:#{code} (03)"',
      '    }',
      '',
      '    if (amount * 0.5 <= 50) {',
      '      "# code:#{code} (04)"',
      '    } elseif (100 < amount + 1 && amount - 1 < 200) {',
      '      "# code:#{code} (05)"',
      '    } else {',
      '      "# code:#{code} (06)"',
      '    }',
      '',
      '    if (amount * amount / 10000 > 2 * (1 + 1)) {',
      '      "# code:#{code} (07)"',
      '    }',
      '',
      '    if ((1 == 1) == true) {',
      '      "# code:#{code} (08)"',
      '    }',
      '    if ((1 == 1) == (2 == 2)) {',
      '      "# code:#{code} (09)"',
      '    }',
      '    if ((1 >= 1) == (2 < 3)) {',
      '      "# code:#{code} (10)"',
      '    }',
      '  }',
      '}',
    ],
    output: [
      '# code:100 (01)',
      '# code:100 (02)',
      '# code:100 (04)',
      '# code:100 (08)',
      '# code:100 (09)',
      '# code:100 (10)',
      '# code:200 (01)',
      '# code:200 (02)',
      '# code:200 (05)',
      '# code:200 (08)',
      '# code:200 (09)',
      '# code:200 (10)',
      '# code:300 (01)',
      '# code:300 (02)',
      '# code:300 (06)',
      '# code:300 (07)',
      '# code:300 (08)',
      '# code:300 (09)',
      '# code:300 (10)',
    ],
  },
];
