module.exports = [
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '  }',
      '  output {',
      '    "- {name}"',
      '  }',
      '}',
    ],
    output: [
    ],
  },
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '  }',
      '  output {',
      '  }',
      '}',
    ],
    output: [
    ],
  },
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy']],
      ['200', 'item02', 200, ['zzz']],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '  }',
      '  output {',
      '    "# code:#{code} {#{name},#{amount}}"',
      '    for (comment in comments) {',
      '      "- #{comment}"',
      '    }',
      '  }',
      '}',
    ],
    output: [
      '# code:100 {item01,100}',
      '- xxx',
      '- yyy',
      '# code:200 {item02,200}',
      '- zzz',
    ],
  },
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
      ['200', 'item02', 200, ['zzz']],
      ['300', 'item03', 300, []],
      ['400', 'item04', 400, []],
    ],
    input: [
      'report {',
      ' ',
      '  code {',
      ' ',
      '    100',
      ' ',
      '    200',
      '    300',
      ' ',
      '  }',
      ' ',
      '  output {',
      '    if (amount <= 100) {',
      '      "# code:#{code} {#{name},#{amount}}"',
      ' ',
      '      for (comment in comments) {',
      '        if (comment != "yyy") {',
      '          "- #{comment}"',
      '        }',
      '      }',
      '    } elseif (amount < 300) {',
      '    } else {',
      '      "# code:#{code} {#{name},#{amount}} (excess)"',
      '    }',
      '  }',
      ' ',
      '}',
    ],
    output: [
      '# code:100 {item01,100}',
      '- xxx',
      '- zzz',
      '# code:300 {item03,300} (excess)',
    ],
  },
  {
    items: [
      ['100', 'item01', 100, ['xxx', 'yyy', 'zzz']],
      ['200', 'item02', 200, ['zzz']],
      ['300', 'item03', 300, ['yyy', 'zzz']],
    ],
    input: [
      'report {',
      ' ',
      '  code {',
      '    100',
      '    200',
      '    300',
      '  }',
      ' ',
      '  output {',
      '    if (amount * 0.5 <= 50) {',
      '      "# code:#{code} (a)"',
      '    } elseif (100 < amount + 1 && amount - 1 < 200) {',
      '      "# code:#{code} (b)"',
      '    } else {',
      '      "# code:#{code} (c)"',
      '    }',
      '  }',
      ' ',
      '}',
    ],
    output: [
      '# code:100 (a)',
      '# code:200 (b)',
      '# code:300 (c)',
    ],
  },
  {
    items: [
      ['100', 'item01', 100],
      ['200', 'item02', 200],
    ],
    input: [
      'report {',
      '  code {',
      '    100',
      '    200',
      '  }',
      '  output {',
      '    "- ##{amount}#"', // double quote
      "    '- ##{amount}#'", // single quote
      '  }',
      '}',
    ],
    output: [
      '- #100#',
      '- #100#',
      '- #200#',
      '- #200#',
    ],
  }
];
